### ISSUE TITLE
Confirm password for Sign Up page

### ISSUE THREAD

**Issue by Pet3r1512** [Grace-Rasaily780/boringfinance#3]
Personally, I think Sign up page should have extra input for "Confirm password" in case users type their password incorrectly. Then they have to reset the password.

To prevent that, a "confirm password" input to check users type password correctly twice.

**Comment by Grace-Rasaily780** [comment]
@Pet3r1512,
Appreciate your suggestion, I will update the input field for a confirm password to enhance the user security and experience. Thank you so much for the time and insight.

Thank you,
A Wannabe
Grace Rasaily
