### ISSUE TITLE
Modal closing after clicking on save

### ISSUE THREAD

**Issue by baibhavKumar1** [Grace-Rasaily780/boringfinance#5]
![image](https://github.com/user-attachments/assets/0f1bd914-20e7-49bf-82e3-df0143edfdb1)

## Issue

User needs to click on close after clcking on save after saving settings.

## Fix

Modal can be closed after clicking on `Save Changes`.

**Comment by Grace-Rasaily780** [comment]
@baibhavKumar1,
Thank you for your insight. It is a small thing that really makes an impact. I will definitely update that in the next commit.

Again thank you for the issue raised.

Thank you,
A Wannabe
Grace Rasaily
